baseURL: https://shinydevseries.com
theme: "hugo-apero"
languageCode: en
title: Shiny Developer Series
author: Eric Nantz
copyright: 'Eric Nantz'
googleAnalytics: ''
disqusShortname: ''
metaDataFormat: yaml
footnoteReturnLinkContents: '&#8617;'
paginate: 5
preserveTaxonomyNames: yes
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
  - "(^|/)renv$"
  - "renv\\.lock$"
enableEmoji: yes
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      hardwraps: no
      unsafe: yes
  highlight:
    style: github
  tableOfContents:
    endLevel: 2
    ordered: no
    startLevel: 2
params:
  custom_theme: "shinydevseries"
  customheadingFontFamily: 'Rajdhani'
  customtextFontFamily: 'Saira'
  #customheadingFontFamily: ''
  #customtextFontFamily: ''
  description: Description for Shiny Dev Series.
  favicon: /img/favicon.ico
  #headingFontFamily: 'serif'
  #textFontFamily: 'sans-serif'
  headingFontFamily: ''
  textFontFamily: ''
  logo: /img/shinydevseries_hex.png
  mainSections:
    #- blog
    - interview
    - guest
    #- project
  math:
    renderer: katex
  navallcaps: yes
  orgLocal: Anywhere
  orgName: RStudio
  sharing_image: /img/shinydevseries_hex.png
  social:
    - icon: github
      icon_pack: fab
      url: https://github.com/shinydevseries/shinydevseries_site
    - icon: twitter
      icon_pack: fab
      url: https://twitter.com/shinydevseries
    - icon: youtube
      icon_pack: fab
      url: https://youtube.com/shinydeveloperseries
    - icon: rss
      icon_pack: fas
      url: /blog/index.xml
    - icon: twitch
      icon_pack: fab
      url: https://twitch.tv/rpodcast
    - icon: microphone
      icon_pack: fas
      url: https://r-podcast.org
  socialInFooter: yes
  socialInHeader: no
  theme: ''
  twitter: shinydevseries
  utterances:
    issue_term: pathname
    label: 'comments :crystal_ball:'
    repo_name: shinydevseries/shinydevseries_site
    theme: photon-dark
    use_utterances: yes
taxonomies:
  category: categories
  series: series
  tag: tags
menu:
  footer:
    - name: License
      title: License
      url: /license/
      weight: 1
  header:
    - name: About
      title: About Blogophonic
      url: /about/
      weight: 3
#    - name: Blog
#      title: Blog
#      url: /blog/
#      weight: 4
    - name: Interviews
      title: Interviews
      url: /interview/
      weight: 1
    - name: Guests
      title: Interview Guests
      url: /guest/
      weight: 2
    - name: Contact
      title: Contact form
      url: /contact/
      weight: 4
#    - name: A collection
#      title: A collection
#      url: /collection/
#      weight: 5
#    - name: Elements
#      title: Element Page
#      url: /elements/
#      weight: 6
privacy:
  disqus:
    disable: no
  googleAnalytics:
    anonymizeIP: yes
    disable: no
    respectDoNotTrack: yes
  instagram:
    disable: no
    simple: yes
  twitter:
    disable: no
    enableDNT: yes
    simple: no
  vimeo:
    disable: no
    enableDNT: yes
    simple: yes
  youtube:
    disable: no
    privacyEnhanced: yes
