# This file was generated by the {rix} R package v0.17.2 on 2025-09-23
# with following call:
# >rix(r_ver = "4.5.1",
#  > r_pkgs = c("rmarkdown",
#  > "knitr",
#  > "quarto",
#  > "yaml",
#  > "jsonlite",
#  > "rix",
#  > "shiny",
#  > "shinylive",
#  > "gfonts",
#  > "shinystate",
#  > "roxy.shinylive"),
#  > system_pkgs = "quarto",
#  > ide = "none",
#  > project_path = getwd(),
#  > overwrite = TRUE)
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-09-22.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      gfonts
      jsonlite
      knitr
      quarto
      rix
      rmarkdown
      roxy_shinylive
      shiny
      shinylive
      shinystate
      yaml;
  };
      
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      quarto
      R
      which
      pandoc;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ rpkgs system_packages ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
